### ISSUE TITLE
License

### ISSUE THREAD

**Issue by simonft** [johnspurlock/app-privacy-report-viewer#8]
This project is super helpful and interesting, thanks!

Are you intending on making this available under any sort of open source license, in case some of the code ends up being useful in other projects?

**Comment by johnspurlock** [comment]
Yep I'm fine with that, just licensed as MIT.  Did you have a project in mind?

This started as a weekend project during the early iOS 15 betas, honestly had no idea it would remain useful for this long.

The reason it's open-source here and deliberately simplistic is due to the possibly sensitive nature of the underlying data.  I personally would not recommend using _any_ 3rd-party opaque binary app, including iOS apps, to process it.

The fact that this project is five small typescript files that are trivially auditable, and the fact that it runs transparently on your local machine using Deno, makes it something I would use myself, even I didn't happen to write it.

**Comment by simonft** [comment]
Great, thanks. We have some ideas for projects, but nothing we're ready to talk about publicly yet. It might not end up using any code in here but I figured others might find it useful. And yeah, we're aware of and thinking about the privacy concerns.

I'll open a PR adding a license file to the repo with the MIT/Expat license.

**Comment by simonft** [comment]
Never mind, I see you already added a license file in 62f1e4da4d77bd1daa7866d27703c02b26ae4259. Thanks!
